using Auran.Clinic.Api.Contracts.Clinics;
using Auran.Clinic.Api.Contracts.Features;
using Auran.Clinic.Api.Contracts.Files;
using Auran.Clinic.Api.Mappings;
using Auran.Clinic.Application.Authorization;
using Auran.Clinic.Application.Clinics;
using Auran.Clinic.Application.Features;
using Auran.Clinic.Application.Files;
using Auran.Clinic.Application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace Auran.Clinic.Api.Controllers;

[ApiController]
[Route("api/platform-clinics")]
[Produces("application/json")]
[Authorize(Policy = ActorPolicies.Platform)]
public sealed class PlatformClinicsController(
    IPlatformClinicService clinicService,
    IFileService fileService) : ControllerBase
{
    [HttpPost("create")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.Create)]
    [SwaggerOperation(
        Summary = "Provision a clinic",
        Description = "Platform-only transactional clinic provisioning. The final Clinic.Code is generated by the backend and cannot be supplied by the caller. Required clinic identity/contact/localization fields, default settings, feature mappings, protected roles, permissions and the first clinic Admin account are created atomically.",
        OperationId = "PlatformClinics_Create",
        Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse<ClinicDetailsResponse>), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<BaseResponse<ClinicDetailsResponse>>> Create(
        [FromBody] CreateClinicApiRequest request,
        CancellationToken cancellationToken)
    {
        var result = await clinicService.CreateAsync(request.ToServiceRequest(), cancellationToken);
        if (!result.Succeeded)
        {
            var response = Error(result.Error ?? "Clinic provisioning failed.");
            return result.IsConflict ? Conflict(response) : BadRequest(response);
        }

        return CreatedAtAction(nameof(GetById), new { id = result.Clinic!.Id }, new BaseResponse<ClinicDetailsResponse>
        {
            Status = true,
            Message = "Clinic provisioned successfully.",
            Data = result.Clinic
        });
    }

    [HttpGet("search")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.View)]
    [SwaggerOperation(Summary = "Search clinics", Description = "Platform-only paginated clinic search across tenants. Supports text and active-state filters and does not expose clinical patient data.", OperationId = "PlatformClinics_Search", Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse<PaginatedResponse<ClinicSummaryResponse>>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<BaseResponse<PaginatedResponse<ClinicSummaryResponse>>>> Search(
        [FromQuery] ClinicSearchApiRequest request,
        CancellationToken cancellationToken)
    {
        return Ok(new BaseResponse<PaginatedResponse<ClinicSummaryResponse>>
        {
            Status = true,
            Data = await clinicService.SearchAsync(request.ToServiceRequest(), cancellationToken)
        });
    }

    [HttpGet("get/{id:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.View)]
    [SwaggerOperation(Summary = "Get clinic administration details", Description = "Returns tenant identity, configuration and initial Admin summary for platform administration. It does not expose patient or clinical records.", OperationId = "PlatformClinics_GetById", Tags = new[] { "Platform Clinics" })]
    public async Task<ActionResult<BaseResponse<ClinicDetailsResponse>>> GetById(Guid id, CancellationToken cancellationToken)
    {
        var result = await clinicService.GetByIdAsync(id, cancellationToken);
        return result is null
            ? NotFound(new BaseResponse { Status = false, Message = "Clinic was not found." })
            : Ok(new BaseResponse<ClinicDetailsResponse> { Status = true, Data = result });
    }

    [HttpPut("update/{id:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.Update)]
    [SwaggerOperation(
        Summary = "Update clinic administration data",
        Description = "Replaces the mutable clinic administration data using the same core clinic profile fields used during creation. Generated Clinic.Code, CodePrefix, clinic Id, initial Admin credentials and activation state are intentionally not accepted here and cannot be changed by this operation.",
        OperationId = "PlatformClinics_Update",
        Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<BaseResponse>> Update(
        Guid id,
        [FromBody] UpdateClinicApiRequest request,
        CancellationToken cancellationToken)
    {
        try
        {
            return await clinicService.UpdateAsync(id, request.ToServiceRequest(), cancellationToken)
                ? Ok(new BaseResponse { Status = true, Message = "Clinic updated successfully." })
                : NotFound(new BaseResponse { Status = false, Message = "Clinic was not found." });
        }
        catch (InvalidOperationException ex)
        {
            return Conflict(Error(ex.Message));
        }
    }

    [HttpPost("create-branding-upload-session/{id:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.Update)]
    [SwaggerOperation(
        Summary = "Create a clinic branding image upload session",
        Description = "Platform-only upload flow for clinic branding images such as the clinic logo. Supports PNG, JPEG and WEBP. Upload the raw bytes to the returned temporary UploadUrl, complete the session, then use the returned URL in the clinic update request.",
        OperationId = "PlatformClinicBranding_CreateUploadSession",
        Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse<FileUploadSessionResponse>), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<BaseResponse<FileUploadSessionResponse>>> CreateBrandingUploadSession(
        Guid id,
        [FromBody] CreateFileUploadSessionApiRequest request,
        CancellationToken cancellationToken)
    {
        try
        {
            var result = await fileService.CreateClinicBrandingUploadSessionAsync(id, request.ToServiceRequest(), cancellationToken);
            return result is null
                ? NotFound(new BaseResponse { Status = false, Message = "Clinic was not found." })
                : StatusCode(StatusCodes.Status201Created, new BaseResponse<FileUploadSessionResponse>
                {
                    Status = true,
                    Message = "Clinic branding upload session created.",
                    Data = result
                });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(Error(ex.Message));
        }
    }

    [HttpPost("complete-branding-upload-session/{id:guid}/{sessionId:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.Update)]
    [SwaggerOperation(
        Summary = "Complete a clinic branding image upload",
        Description = "Completes a Platform-created clinic branding upload session and returns the permanent FileId, metadata and URL. The returned URL can be stored as LogoUrl in the clinic update request.",
        OperationId = "PlatformClinicBranding_CompleteUploadSession",
        Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse<FileResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<BaseResponse<FileResponse>>> CompleteBrandingUploadSession(
        Guid id,
        Guid sessionId,
        CancellationToken cancellationToken)
    {
        try
        {
            var result = await fileService.CompleteClinicBrandingUploadAsync(id, sessionId, cancellationToken);
            return result is null
                ? NotFound(new BaseResponse { Status = false, Message = "Clinic branding upload session was not found." })
                : Ok(new BaseResponse<FileResponse>
                {
                    Status = true,
                    Message = "Clinic branding image uploaded successfully.",
                    Data = result
                });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(Error(ex.Message));
        }
    }

    [HttpPut("set-status/{id:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.SetStatus)]
    [SwaggerOperation(Summary = "Set clinic status", Description = "Activates or suspends a clinic. Suspension is enforced on subsequent clinic requests, including requests using previously issued JWTs, through the centralized clinic access guard.", OperationId = "PlatformClinics_SetStatus", Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<BaseResponse>> SetStatus(
        Guid id,
        [FromBody] SetClinicStatusApiRequest request,
        CancellationToken cancellationToken)
    {
        var serviceRequest = request.ToServiceRequest();
        return await clinicService.SetActiveAsync(id, serviceRequest.IsActive, cancellationToken)
            ? Ok(new BaseResponse { Status = true, Message = serviceRequest.IsActive ? "Clinic activated." : "Clinic suspended." })
            : NotFound(new BaseResponse { Status = false, Message = "Clinic was not found." });
    }

    [HttpGet("get-features/{id:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.View)]
    [SwaggerOperation(Summary = "Get clinic features", Description = "Returns the global feature catalog projected with enabled state and per-clinic configuration for the selected clinic.", OperationId = "PlatformClinicFeatures_Get", Tags = new[] { "Platform Clinics" })]
    public async Task<ActionResult<BaseResponse<IReadOnlyCollection<ClinicFeatureResponse>>>> GetFeatures(Guid id, CancellationToken cancellationToken)
    {
        var result = await clinicService.GetFeaturesAsync(id, cancellationToken);
        return result is null
            ? NotFound(new BaseResponse { Status = false, Message = "Clinic was not found." })
            : Ok(new BaseResponse<IReadOnlyCollection<ClinicFeatureResponse>> { Status = true, Data = result });
    }

    [HttpPut("update-features/{id:guid}")]
    [Authorize(Policy = PermissionPolicy.PlatformPrefix + Permissions.Platform.Clinics.ManageFeatures)]
    [SwaggerOperation(Summary = "Update clinic features", Description = "Platform-only feature entitlement management. Feature state is independent from clinic RBAC permissions and cache entries are invalidated immediately after changes.", OperationId = "PlatformClinicFeatures_Update", Tags = new[] { "Platform Clinics" })]
    [ProducesResponseType(typeof(BaseResponse), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<BaseResponse<IReadOnlyCollection<ClinicFeatureResponse>>>> UpdateFeatures(
        Guid id,
        [FromBody] UpdateClinicFeaturesApiRequest request,
        CancellationToken cancellationToken)
    {
        var result = await clinicService.UpdateFeaturesAsync(id, request.ToServiceRequest(), cancellationToken);
        return result is null
            ? NotFound(new BaseResponse { Status = false, Message = "Clinic was not found." })
            : Ok(new BaseResponse<IReadOnlyCollection<ClinicFeatureResponse>> { Status = true, Data = result });
    }

    private static BaseResponse Error(string message) => new()
    {
        Status = false,
        Message = message,
        Error = message
    };
}
